### ISSUE TITLE
Firefox in full OpenGL compositing mode artifacts on 4.6

### ISSUE THREAD

**Issue by valpackett** [FreeBSDDesktop/freebsd-base-graphics#58]
So I just upgraded my Haswell Thinkpad from normal -CURRENT to `drm-next-4.6` (52ae720).
- `*ERROR* timeout waiting for SBI to complete read transaction` dmesg spam (that slowed down booting for a couple seconds) is gone
- New dmesg spam: `hdac0: Unexpected unsolicited response from address 0: 00000000` at the end of the boot process, right before the login prompt, and not taking any time
- No more `GPU hung` crap when starting X! Nice :)
- clinfo doesn’t show `self-test failed` anymore
- [Chlorine](https://github.com/Polytonic/Chlorine) OpenCL Mandelbrot demo still works
- VAAPI video decoding acceleration still works
- Hotplugging external displays still works… kinda. After connecting my HDMI TV, Xorg was frozen for, like, a minute. But works after that.
- shadertoy still renders fine in both Firefox and Chromium
- ioquake3 still works
- #51 panic on OpenMW
- **Firefox with full OpenGL accelerated compositing enabled (`layers.acceleration.force-enable`) is artifacting heavily** (tried switching to UXA, didn't help. Switched acceleration off for now)

![screen_2016-08-01-11 10 13](https://cloud.githubusercontent.com/assets/208340/17291760/d84956ba-57f6-11e6-9708-6e5b6feb9a18.png)

BTW, what's the thing with using `modesetting` instead of `intel` in Xorg? I tried that — got slow software rendering (llvmpipe)! Maybe I need xserver-next ports…

**Comment by valpackett** [comment]
UPDATE: figured it out: `modesetting` should be used with `Option     "AccelMethod"          "glamor"`.

So with `xserver-next`, both UXA and SNA are crap. SNA results in some corrupt text in the terminal, and UXA results in artifacts.

But Glamor works well. Except there's tearing. Even a new, exciting kind of tearing, never seen with `xf86-video-intel` — diagonal!

Compositing usually helps, but compton only works with the xrender backend (which is useless in terms of vsync) when used with Glamor.
The hybrid backend results in a black screen and the GLX backend results in this nice rendering mode:
![screenshot](https://cloud.githubusercontent.com/assets/208340/17294439/e7495550-5807-11e6-89ef-407d0f54303e.jpg)

:D

**Comment by nomadlogic** [comment]
are you using the latest Xorg from this git repo?
https://github.com/freebsd/freebsd-ports-graphics/tree/xserver-next

I've had issues using glamor on skylake (as well as haswell oddly enough) so it'd be interesting to know if you are able to force glamor rendering using the xserver-next branch.

**Comment by valpackett** [comment]
@nomadlogic I _am_ using glamor and xserver-next, that's what I said in the update comment ;-)

It's mostly fine. Though there's tearing. And some artifacts in Firefox:
- multiprocess disabled, full acceleration enabled: persistent artifacts like on the screenshot in the first post
- multiprocess enabled, full acceleration disabled: intermittent artifacts that are usually cleared by moving the window
- both features disabled: no artifacts (maybe I saw the intermittent ones, but very rarely)

If you get a black screen, make sure you don't use a GLX compositor.

**Comment by nomadlogic** [comment]
d'oh must have missed that.  

out of curiosity are you getting the following error in /var/log/Xorg.0.log by any chance?

`[  6735.747] (WW) modeset(0): DRI2: glamor lacks support for pixmap import/export
`

**Comment by valpackett** [comment]
No, I'm not getting that error

**Comment by valpackett** [comment]
Switched back to `intel` / SNA (because artifacts weren't as rare with glamor as I first thought) — not seeing any text corruption in the terminal. Everything seems to be fine except the Firefox full acceleration thing.

**Comment by mattmacy** [comment]
The acceleration issue with Firefox is a firefox configuration / ports problem that you'll need to take up with the porters. Chromium has full offload capabilities which I've left running 2k videos on Youtube overnight (the X1's 14" display only does up to 2560x1440).

**Comment by valpackett** [comment]
@mattmacy wait, are you thinking of video acceleration? No no no, I was talking about **compositing** acceleration, look at the screenshot in the first post here.

**Comment by mattmacy** [comment]
Ahh - well, try it on chromium. It has almost all acceleration enabled by default.

**Comment by valpackett** [comment]
Why chromium? I'm saying that **Firefox UI gets covered in permanent artifacts after updating from i915 3.8 to 4.6** (when full OpenGL compositing is enabled instead of the "Basic" cairo/xrender stuff)!
![](https://cloud.githubusercontent.com/assets/208340/17291760/d84956ba-57f6-11e6-9708-6e5b6feb9a18.png)

Chromium is even worse, it's glitching like this:
![](https://cloud.githubusercontent.com/assets/208340/17307870/3bce68e6-5848-11e6-8874-5d0bade29ef3.jpg)

Right now (xorg-newest, SNA) it's not _as_ bad, the background is white at least, but it's still messed up.

**Comment by mattmacy** [comment]
Strange. I guess I've never tried full OpenGL compositing - I've never had any issues with SNA on Haswell. Does it seem to work OK otherwise?

**Comment by valpackett** [comment]
Yes, Firefox renders perfectly fine when about:support says `GPU Accelerated Windows    0/1 Basic (OMTC)` (so, with `layers.acceleration.force-enabled` set to `false`).

Chromium is messed up though.
![screen_2016-08-01-23 34 28](https://cloud.githubusercontent.com/assets/208340/17308154/9818c866-5849-11e6-9407-363c95650204.png)

And scrolling in Thunar or the file picker in Firefox now results in a weird X error… This started happening after changing GTK themes in XFCE, but I'm not sure that can affect anything…
![screen_2016-08-01-23 38 22](https://cloud.githubusercontent.com/assets/208340/17308161/a10ad70c-5849-11e6-85da-464c873d68e3.png)

Interestingly, Nautilus is fine.

**Comment by mattmacy** [comment]
Are you using firefox and chromium built from xserver-next? I used to see that error with Firefox.
If you're running xserver-next, all your ports should be built against it.

As an aside, I've found that setting GDK_SYNCHRONIZE makes the problem go away.

**Comment by valpackett** [comment]
Some SNA text corruption…

![screen_2016-08-01-23 44 20](https://cloud.githubusercontent.com/assets/208340/17308297/4f85ca62-584a-11e6-877f-0c50df049bcb.png)

**Comment by mattmacy** [comment]
And it probably won't fix any of your issues, but please test with the latest sources.

**Comment by valpackett** [comment]
Nah, I'm still using everything from pkg except dri, libGL, libEGL, libdrm, libglapi, xorg-server, xf86-*. I'll try rebuilding the browsers now…

Latest sources of what? The kernel? I'm running what was the latest about 25 hours ago…

**Comment by valpackett** [comment]
Though… wait, I've pulled from `freebsd/freebsd-base-graphics` not `FreeBSDDesktop/freebsd-base-graphics` then! Damn.

**Comment by mattmacy** [comment]
The change you referred to at the top is 9 days old. Furthermore, I fixed a number of bugs yesterday evening.

http://www.bsddesktop.com/images/120amd64-ports-graphics-xserver-mesa-next/

**Comment by valpackett** [comment]
Why do both `freebsd/freebsd-base-graphics` and `FreeBSDDesktop/freebsd-base-graphics` exist, anyway?

**Comment by mattmacy** [comment]
freebsd/freebsd-base-graphics was what Jean used. Only committers have access to freebsd/

**Comment by valpackett** [comment]
So after fully upgrading to Mesa 12 from that repo (I had libGL/EGL 11 when I built them myself), and browsers from that repo: Compton's GLX backend works on Glamor! (But I can't eliminate Glamor tearing even with compton GLX vsync…)

Chromium and Firefox issues are still present.

Interestingly, launching Chromium adds artifacting to Firefox (and restarting Firefox fixes it).

**Comment by mattmacy** [comment]
Ok, but does Chromium have issues running by itself under SNA?

**Comment by mattmacy** [comment]
I'm trying to figure out if you're seeing fundamentally different behavior from what I am. So far you've been running different configurations / package sets. And have you updated your kernel too?

**Comment by valpackett** [comment]
Currently compiling the kernel.

Chromium is glitching on all three acceleration modes!

**Comment by mattmacy** [comment]
What DE / WM are you running?

**Comment by valpackett** [comment]
XFCE4 + compton (but killing compton or switching compton backends doesn't make a difference)

Here's what SNA does sometimes:
![screen_2016-08-02-02 12 22](https://cloud.githubusercontent.com/assets/208340/17311859/74660b5c-585f-11e6-9b45-79450289a76d.png)
![screen_2016-08-02-02 10 47](https://cloud.githubusercontent.com/assets/208340/17311862/77858600-585f-11e6-817f-82b14d024b2a.png)

Glamor instead has diagonal tearing, which is better than not being able to read text :D

Chromium does the triangles glitch on both.

**Comment by valpackett** [comment]
Oh, Glamor also does this sometimes:
![screen_2016-08-02-02 18 12](https://cloud.githubusercontent.com/assets/208340/17311920/d2d1f61a-585f-11e6-9601-5a014191fba4.png)

But that's not permanent, it goes away after moving the window around

**Comment by mattmacy** [comment]
What happens just running xfce w/o compton to begin with? I've never seen issues with xfce.

And how does one enable compton?

**Comment by mattmacy** [comment]
Yes, clearly Glamor needs KMS work. Unfortunately, not sure how to troubleshoot that problem.

**Comment by valpackett** [comment]
I have compton in my xinitrc. Running without it didn't change anything, just as expected. It's not a compositor thing, it's a 2D acceleration thing.

Glamor is better than SNA right now! SNA corrupts text :(

**Comment by mattmacy** [comment]
I'll need to figure out what's special/different about your system.

**Comment by mattmacy** [comment]
Does your system work ok with the 3.8 driver in HEAD?

**Comment by valpackett** [comment]
Maybe I just don't have all the right userspace packages…

On 3.8 everything was perfect.

**Comment by mattmacy** [comment]
It's possible. If you're not careful to disable the default repo pkg will interleave packages from multiple repos giving you a truly rubbish setup.

**Comment by mattmacy** [comment]
It's literally bad enough that I may not publish my repo because I can't rely on people to pay close enough attention. Check that all your X11 packages are actually the ones in the repo.

**Comment by valpackett** [comment]
Oh — I wasn't even able to use the repo in pkg (even after `pkg clean -a && pkg update -f`):

```
Fetching xorg-server-1.18.4,1.txz: 100%    1 MiB 501.9kB/s    00:03
pkg: cached package xorg-server-1.18.4,1: size mismatch, fetching from remote
Fetching xorg-server-1.18.4,1.txz: 100%    1 MiB 501.9kB/s    00:03
pkg: cached package xorg-server-1.18.4,1: size mismatch, cannot continue
```

I've been manually downloading the packages and using `pkg add -f`.

The repo config I tried:

```
Gfx: {
  url: "http://www.bsddesktop.com/images/120amd64-ports-graphics-xserver-mesa-next/",
  enabled: yes,
  priority: 100
}
```

(BTW, plain HTTP and no signatures… that makes me sad)

It'd be much better if you provided a _list_ of "X11 packages" that need to be reinstalled.

**Comment by mattmacy** [comment]
You're welcome to build your own 😃

I had never used poudriere prior to recent graphics work. If you can provide a howto on configuring signatures and SSL with nginx I'll follow up. I just don't have the time to figure that out.

As for packages needed I'll have to draw up a list it's only recently that people seem to be frequently creating broken installs. I ended up uninstalling most of my X related packages and just doing a pkg add in the All directory locally. Pkg has made huge strides, but it's a long way from apt/yum.

**Comment by valpackett** [comment]
[lua-resty-auto-ssl](https://github.com/GUI/lua-resty-auto-ssl)? For signatures, I mean pkg's built-in signature checking.

**Comment by mattmacy** [comment]
I ran poudriere, it generated that output. So obviously signature generation is not the default. I'll look at resty, but I doubt that's it's a one line addition to the config file.

**Comment by valpackett** [comment]
Installed these packages from the repo:

```
argyllcms-1.7.0_1.txz                  libdevq-0.0.3_2.txz                    libXmu-1.1.2_3,1.txz                   xcb-util-0.4.0_1,1.txz
atk-2.18.0.txz                         libdrm-2.4.69,1.txz                    libXp-1.0.3,1.txz                      xcb-util-image-0.4.0_1.txz
atkmm-2.22.7.txz                       libEGL-12.0.1.txz                      libXpm-3.5.11_4.txz                    xcb-util-keysyms-0.4.0_1.txz
beignet-1.1.2.txz                      libFS-1.0.7.txz                        libXrandr-1.5.0.txz                    xcb-util-renderutil-0.3.9_1.txz
cairomm-1.10.0_3.txz                   libGL-12.0.1.txz                       libXrender-0.9.9.txz                   xcb-util-wm-0.4.1_3.txz
chromium-51.0.2704.106_2.txz           libglapi-12.0.1.txz                    libXres-1.0.7_3.txz                    xcmiscproto-1.2.2.txz
damageproto-1.2.1.txz                  libglesv2-12.0.1.txz                   libXScrnSaver-1.2.2_3.txz              xdg-utils-1.1.1.txz
dmxproto-2.3.1.txz                     libGLU-9.0.0_2.txz                     libXt-1.1.5,1.txz                      xdriinfo-1.0.5.txz
dri-12.0.1,2.txz                       libICE-1.0.9_1,1.txz                   libXTrap-1.0.1_3.txz                   xextproto-7.3.0.txz
dri2proto-2.8.txz                      libIDL-0.8.14_2.txz                    libXtst-1.2.2_3.txz                    xf86-input-keyboard-1.8.1_1.txz
firefox-47.0.1_2,1.txz                 libSM-1.2.2_3,1.txz                    libXv-1.0.10_3,1.txz                   xf86-input-mouse-1.9.1_2.txz
fixesproto-5.0.txz                     libva-1.7.1.txz                        libXvMC-1.0.9.txz                      xf86-video-intel-2.99.917.20160614.txz
fontcacheproto-0.1.3.txz               libvdpau-1.1.1.txz                     libXxf86dga-1.1.4_3.txz                xf86bigfontproto-1.2.0.txz
fontconfig-2.11.1_2,1.txz              libX11-1.6.3,1.txz                     libXxf86misc-1.0.3_3.txz               xf86dga-1.0.3_1.txz
fontsproto-2.1.3,1.txz                 libXau-1.0.8_3.txz                     libXxf86vm-1.1.4_1.txz                 xf86dgaproto-2.1.txz
freeglut-3.0.0.txz                     libXaw-1.0.13,2.txz                    mesa-demos-8.3.0.txz                   xf86driproto-2.1.1.txz
freetype2-2.6.3.txz                    libxcb-1.11.1.txz                      ocl-icd-2.2.7.txz                      xf86miscproto-0.9.3.txz
gbm-12.0.1.txz                         libXcomposite-0.4.4_3,1.txz            opencl-2.0.txz                         xf86vidmodeproto-2.3.1.txz
gle-3.1.0_6.txz                        libXcursor-1.1.14_3.txz                OpenEXR-2.2.0_5.txz                    xfce4-appfinder-4.12.0.txz
glew-1.13.0.txz                        libXdamage-1.1.4_3.txz                 pango-1.38.0_1.txz                     xfce4-conf-4.12.0.txz
glib-2.46.2_2.txz                      libXdmcp-1.1.2.txz                     pangomm-2.36.0.txz                     xfce4-desktop-4.12.3.txz
glib-networking-2.46.1_1.txz           libXevie-1.0.3_3.txz                   pixman-0.34.0.txz                      xfce4-notifyd-0.2.4_1.txz
glibmm-2.44.0,1.txz                    libXext-1.3.3_1,1.txz                  presentproto-1.0.txz                   xfce4-panel-4.12.0_1.txz
glproto-1.4.17.txz                     libxfce4menu-4.12.1_1.txz              printproto-1.0.5.txz                   xfce4-session-4.12.1_3.txz
gtk-engines2-2.20.2_2.txz              libxfce4util-4.12.1.txz                randrproto-1.5.0.txz                   xfce4-settings-4.12.0_1.txz
gtk-murrine-engine-0.98.2_4.txz        libXfixes-5.0.1_3.txz                  recordproto-1.14.2.txz                 xfce4-tumbler-0.1.31_2.txz
gtk-xfce-engine-3.2.0.txz              libXfont-1.5.1,2.txz                   renderproto-0.11.1.txz                 xfce4-wm-4.12.3.txz
gtk2-2.24.29_2.txz                     libXfontcache-1.0.5_3.txz              resourceproto-1.2.0.txz                xinit-1.3.4,1.txz
gtk3-3.18.8_3.txz                      libXft-2.3.2_1.txz                     scrnsaverproto-1.2.2.txz               xkbcomp-1.3.1.txz
gtksourceview2-2.10.5_4.txz            libXi-1.7.6,1.txz                      setxkbmap-1.3.1.txz                    xmodmap-1.0.9.txz
gvfs-1.26.3_2.txz                      libXinerama-1.1.3_3,1.txz              Thunar-1.6.10_1.txz                    xorg-server-1.18.4,1.txz
hal-0.5.14_30.txz                      libxkbcommon-0.5.0_1.txz               videoproto-2.3.2.txz                   xproto-7.0.28.txz
hal-info-20091130.txz                  libxkbfile-1.0.9.txz                   webkit-gtk2-2.4.11_2.txz               xrandr-1.4.3.txz
harfbuzz-1.2.7.txz                     libxkbui-1.0.2_4.txz                   webkit2-gtk3-2.8.5_5.txz               xrdb-1.1.0.txz
lcms2-2.7_2.txz                        libxklavier-5.3_1,1.txz                xcb-proto-1.11_1.txz
```

The kernel is `3c0e357(drm-next-4.6)`.

Glamor broke (it was the best before I did this!!) — fully accelerated Firefox isn't starting, Chromium looks like this:
![screen_2016-08-02-03 16 54](https://cloud.githubusercontent.com/assets/208340/17313096/eb32bc08-5869-11e6-97b4-721ce8d84690.png)

SNA:
![screen_2016-08-02-03 19 03](https://cloud.githubusercontent.com/assets/208340/17313104/f903a400-5869-11e6-9007-8eb6f282ece6.png)

UXA:
![screen_2016-08-02-03 21 02](https://cloud.githubusercontent.com/assets/208340/17313107/fd6a0ae8-5869-11e6-9dc5-cb6e5dd970b6.png)

"Well, this is embarassing" :D

Full Immersive Windows 95 mode to complement the Chicago95 theme :D
![screen_2016-08-02-03 29 33](https://cloud.githubusercontent.com/assets/208340/17313127/15bb5f8e-586a-11e6-9a48-a2d95c000225.png)

So, I have to go to sleep now… Tomorrow I'm installing Windows 10 instead. Just kidding :D Looks like I should go back to normal -CURRENT.

**Comment by mattmacy** [comment]
-CURRENT sounds like the way to go. However, before you go could you please post the output of notebookstats, your xorg.conf, and your .xinitrc just in case it's a hardware<->kms issue. Thanks.

Sorry it didn't work out.

**Comment by valpackett** [comment]
https://gist.github.com/myfreeweb/23e6497fc12a6c90e9c0dca4bec8d5d5

Thanks for your work, hopefully the experience will be better when it lands in -CURRENT.

**Comment by mattmacy** [comment]
> Thanks for your work, hopefully the experience will be better when it lands in -CURRENT.

Well, Linux 3.8 was released on April 5, 2013 and the corresponding update to FreeBSD was committed to HEAD on March 8, 2016. Linux 4.6 was released on May 15, 2016. In order to keep pace the corresponding update would need to land in HEAD by April 18, 2019. 

Provided I'm still working on FreeBSD in 3 years I think that's a very achievable goal.

**Comment by abishai** [comment]
On my skylake, sna is the best option, uxa acceleration produces a lot of artifacts and totally unusable. However, I'm running limina which comes with compton. Compton with glx backend produces perfect (yet, I didn't test that much) image, but grabs up to a CPU core, so it's unusable in road warrior setups, compton with xrender produces visible artifacts in windows, like black spots when portion of window was overlapped and some artifacts on window borders. However, issues are minor. 

What is better for testing CURRENT or STABLE branches?  I'd prefer STABLE as I plan to use my laptop, actually, I have no other options as OP as I'm on skylake :)

But I'm amazed that 2016 laptop has so few issues. Looks like the great job was done in 11-STABLE and this branch particular and Dell's ACPI devs. I suppose, I should share stats, XPS13 is a decent choose for FreeBSD even in current state.

**Comment by mattmacy** [comment]
STABLE will only be updated episodically. So your mileage will vary no matter what.

**Comment by abishai** [comment]
I tried CURRENT with DRM 4.7, situation become even worse :)
1. sna - crash on start of any X application. I mean I even can't start anything as most of xfce components (menus, applets) refuse to work. Logs left on work, I can post it if you are interested. Xorg wrote something about bad call.
2. uxa - the same artifacts as for OP.
3. modesetting&glamor - looks like the best option, however I see no mouse cursor, however mouse is operational, just not visible. This one is something new.

**Comment by mattmacy** [comment]
@abishai - you may need to build packages from the xserver-mesa-next branch. I don't see any of those issues.

**Comment by abishai** [comment]
https://github.com/freebsd/freebsd-ports-graphics/tree/xserver-next this repo was used. 
I don't see xserver-mesa-next repo, only mesa-next https://github.com/freebsd/freebsd-ports-graphics/tree/mesa-next Should I switch to it ?

**Comment by mattmacy** [comment]
https://github.com/FreeBSDDesktop/freebsd-ports-graphics

**Comment by abishai** [comment]
I see. I used recipe from wiki  https://github.com/FreeBSDDesktop/freebsd-base-graphics/wiki
I'll retest everything.

**Comment by mattmacy** [comment]
Ok. It's odd that you're seeing such regressions with 4.7.

**Comment by mattmacy** [comment]
I'm using UXA without issue.

**Comment by abishai** [comment]
I mean that wiki suggests another repo for ports.
On newer hardware you will want to install a newer ddx and Xorg. These can be found in the xserver-next branch in the freebsd ports graphics repo:

git clone https://github.com/freebsd/freebsd-ports-graphics -b xserver-next

So, I suppose I have issues due to incorrect repo, as your link points to another one.

**Comment by mattmacy** [comment]
Well, xserver-mesa-next is what we're using now. However, xserver-next from upstream shouldn't be that broken.

**Comment by abishai** [comment]
Well, I used portmaster -af, so everything should be recompiled. I'll try xserver-mesa-next first. Or maybe it's skylake specific problems.

**Comment by mattmacy** [comment]
Make sure the graphics bits are all coming from the newer branch as opposed to master. The most severe issues seem to be a versioning problem.

**Comment by abishai** [comment]
Recompiled xorg-server with deps and intel driver. Graphics bits was definitely different - I saw udev option :P
http://i.imgur.com/U8jPswf.png with uxa
Completely unusable :(
xorg startup log https://gist.github.com/abishai/a828745fe7d6136f5cd1c835f256046b

**Comment by mattmacy** [comment]
@abishai so this worked on drm-next-4.6 but not on drm-next-4.7? Or it never worked?

**Comment by abishai** [comment]
Yep. On drm46-STABLE sna accel was almost usable - only slight artifacts on windows headers when I drag windows.

On drm47-CURRENT
sna - X apps crashing
uxa - artifacts beyond windows contents recognition
modesettings - no mouse cursor (maybe fixable, but cursor was present on sna and uxa tests)

**Comment by mattmacy** [comment]
so when you use drm-next-4.6 now does it not work?

**Comment by abishai** [comment]
I dismantled my drm-next-4.6 BE, so I can't be sure. Do you want me test it on CURRENT ?

**Comment by mattmacy** [comment]
If it still works that's actually interesting. I haven't changed anything in 4.6 in a while, so if it _does_ _not_ work that indicates your install is busted. pkg breaks quite easily with multiple overlapping repos.

**Comment by mattmacy** [comment]
testing 4.6 should be trivial - I can't help you until you do.

**Comment by abishai** [comment]
My repos wasn't overlapped. I completely replaced /usr/src and /usr/ports with git revsions on my tests.

Should I use https://github.com/FreeBSDDesktop/freebsd-base-graphics/tree/drm-next-4.6 with CURRENT?

BTW, I'm using shared ccache persisted for all BE I have on laptop. Can it be the source of problems?

**Comment by mattmacy** [comment]
drm-next-4.6 _is_ -CURRENT + some small changes to sys + graphics drivers

ccache could conceivably lead to versioning issues I would remove any confounding factors, only @myfreeweb is seeing behavior similar to you

**Comment by abishai** [comment]
OK, I'll try with ccache disabled. xserver-mesa-next repo for ports?

**Comment by mattmacy** [comment]
Yes. But make sure all graphics pieces come from there. Mixing with master causes problems.

**Comment by abishai** [comment]
No, the same problems. OK, if you insist this is ports issue, I'm dropping /usr/local and pkg stuff in /var to rebuild everything clean and shiny.
brb :)

**Comment by abishai** [comment]
OK, looks like total cleaning with new compilation solved my problems. sna works fine, now I'm think to migrate to your branch :)
However, I still have the problem of resume with vertical lines. Should I try 4.7 branch ?

**Comment by mattmacy** [comment]
I  haven't done anything to fix resume yet.

**Comment by mattmacy** [comment]
Operator error caused by incorrect ports install.

**Comment by valpackett** [comment]
So, I'm testing 4.7 now.

The thing mentioned in the title of this issue — **Firefox's layer compositing — still artifacts like that**. Gnome-shell, which I guess is doing similar compositing things, has that problem as well. But these things aren't very important (Firefox doesn't use that compositing by default, and GNOME 3 itself is not necessary :D).

The more important missing letters issue: I know a fix! Nothing to do with wrong ports versions.

Actually first I've discovered that Qt applications aren't affected, but GTK 2/3 and pure xlib/xcb are. Started tweaking fontconfig and discovered that **font hinting is to blame for missing letters**. With hinting disabled, there are no missing letters in GTK 2 apps.

GTK 3 apps further required adding `export COGL_ATLAS_DEFAULT_BLIT_MODE=framebuffer` to `.xinitrc` to fix the missing letters.

So, my Xorg desktop is **usable** on 4.7 with SNA, but there's a couple new issues:

- same `vt_kms_postswitch` crash as in #107 happens sometimes!!
- occasionally the screen goes blank for a few seconds. not very often, but happens.

**Comment by mattmacy** [comment]
The postswitch crash is new. Perhaps an artifact of VM changes. I hope to look in to it in the next week or two
